from dataclasses import dataclass, field, asdict
from typing import Optional, Dict, Any
from src import config
from src.utils import helpers, registries

@dataclass
class BaseParams:
    """Container for model, training, and dataset hyperparameters.

    This dataclass centralizes the configuration needed to construct the crowd-counting
    architecture, the data pipeline, and the learning loop. It is used throughout the
    training and registry code to persist, suggest, and reload experiment metadata.

    Attributes:
        image_size (Optional[int]): Target image height/width used by the model.
        crop_size (Optional[int]): Spatial crop size used during training.
        label_scaler (Optional[int]): Scalar applied to density targets for numerical
            stability during optimization and evaluation.
        aug_factor (Optional[float]): Photometric augmentation magnitude.
        num_ops (Optional[int]): Number of random augmentation operations.
        five_crops (bool): Whether to evaluate using a five-crop inference strategy.
        backbone (str): Backbone architecture name used by segmentation models.
        model_class (str): Segmentation model class name.
        backbone_weights (str): Pretrained weights source for the encoder.
        decoder_attention_type (Optional[str]): Attention mechanism for the decoder.
        trainable_backbone (bool): Whether the encoder backbone is fine-tuned.
        neck_out_channels (Optional[int]): Output channels for the feature neck.
        decoder_out_channels (Optional[int]): Output channels for the decoder head.
        dropout (Optional[float]): Dropout probability applied in the decoder.
        batch_size (int): Training mini-batch size.
        val_batch_size (int): Validation/test batch size.
        lr (float): Base learning rate.
        l2_reg (Optional[float]): Weight decay factor for optimizer regularization.
        lr_schedule (Optional[str]): Learning-rate schedule strategy name.
        ssim_weight (Optional[float]): Weight assigned to the SSIM term in composite losses.
        mse_weight (Optional[float]): Weight assigned to the MSE/Huber term in composite losses.
        use_count_loss (Optional[bool]): Whether to apply the MSE/huber on each pixel or on the overall count
        mask_loss_weight (Optional[float]): Weight for the mask-auxiliary loss term.
        huber_delta (Optional[float]): Delta parameter for Huber regression.
        mask_loss_alpha (Optional[float]): Positive-class weight in FocalLoss.
        mask_loss_gamma (Optional[float]): Focal gamma for mask balancing.
        k_threshold (Optional[float]): Threshold used in custom counting logic.
        seg_threshold (Optional[float]): Segmentation threshold for binary masks.
        gt_mask_threshold (Optional[float]): Density threshold used to construct ground
            truth masks.
        use_uncertainty_weighting (bool): Whether learnable uncertainties are used to
            weight loss components.
        monitor_metric (str): Metric name used by early stopping and checkpoints.
        loss_function (str): Selected composite loss function name.
        grad_accumulation (int): Number of micro-batches accumulated before optimizer step.
        grad_clip (Optional[float]): Gradient clipping threshold.
        scheduler_kwargs (Dict[str, Any]): Extra parameters passed to the scheduler.
        suggested_params (bool): Flag indicating the configuration was generated by Optuna.
        epochs (int): Total number of training epochs.
        stop_patience (int): Early stopping patience in epochs.
        check_val_every_n_epoch (Optional[int]): Validation frequency.
        padding_multiple (int): Spatial padding multiple used for model input alignment.
        dataset (str): Dataset name derived from the configured data root.
        train_size (Optional[int]): Size of the training split after dataset partitioning.
        unfrozen_blocks (Optional[tuple]): Encoder blocks kept trainable when fine-tuning.
        optimizer_config (Dict): Optimizer-specific settings.
        extra (Dict): Additional metadata or experiment-specific fields.
    """
    # Image & Data Augmentation
    image_size: Optional[int] = None
    crop_size: Optional[int] = None
    label_scaler: Optional[int] = config.LABEL_SCALER
    aug_factor: Optional[float] = None
    num_ops: Optional[int] = None
    five_crops: bool = False

    # Architecture tweaks
    backbone: str = 'efficientnet-b0'
    model_class: str = 'Unet'
    backbone_weights: str = 'imagenet'
    decoder_attention_type: Optional[str] = None
    trainable_backbone: bool = False
    neck_out_channels: Optional[int] = None
    decoder_out_channels: Optional[int] = None
    dropout: Optional[float] = None

    # Training hardware/flow limits
    batch_size: int = 16
    val_batch_size: int = 32

    # Optimization & Regularization
    lr: float = 0.00065
    l2_reg: Optional[float] = 1e-4
    lr_schedule: Optional[str] = None
    ssim_weight: Optional[float] = None
    mse_weight: Optional[float] = None
    use_count_loss: Optional[bool] = False
    mask_loss_weight: Optional[float] = None
    huber_delta: Optional[float] = None
    mask_loss_alpha: Optional[float] = None
    mask_loss_gamma: Optional[float] = None
    k_threshold: Optional[float] = None
    seg_threshold: Optional[float] = None
    gt_mask_threshold: Optional[float] = None
    use_uncertainty_weighting: bool = False
    # min_lr_pct: Optional[float] = None
    monitor_metric: str = 'val_nae'
    loss_function: str = 'mask_mse_ssim'
    grad_accumulation: int = 1
    grad_clip: Optional[float] = None
    scheduler_kwargs: Dict[str, Any] = field(default_factory=dict)
    suggested_params: bool = False

    # Properties not present in the suggest method (placed last)
    epochs: int = 1
    stop_patience: int = 45
    check_val_every_n_epoch: Optional[int] = 1
    padding_multiple: int = 32
    dataset: str = config.DATASET_PATH.split('/')[-1]
    train_size: Optional[int] = None
    unfrozen_blocks: Optional[tuple] = None
    optimizer_config: Dict = field(default_factory=dict)
    extra: Dict = field(default_factory=dict)

    @classmethod
    def suggest(cls, trial) -> "BaseParams":
        """Sample an Optuna hyperparameter configuration for crowd-counting experiments.

        Args:
            trial: Optuna trial object used to sample categorical, float, and integer
                values for the training setup.

        Returns:
            BaseParams: A configured parameter object that embodies the suggested
                architecture, optimization, and loss settings.

        Raises:
            StopIteration: If no matching backbone entry is discovered in the registry,
                which is handled internally by falling back to ``None`` for the
                unfrozen block list.
        """
        suggested = dict(
            # 1. Architecture & Base Setup (Locked to your current experiment)
            model_class=trial.suggest_categorical('model_class', ['MAnet', 'Unet', 'UnetPlusPlus']),
            backbone=trial.suggest_categorical('backbone', ['tu-convnext_small', 'tu-convnext_base', 'tu-convnextv2_small', 'tu-convnextv2_base', 'efficientnet-b2', 'efficientnet-b4', 'efficientnet-b6']), 
            backbone_weights='imagenet',
            decoder_out_channels=trial.suggest_categorical("decoder_out_channels", [64, 128, 256]),
            
            # 2. Memory & Scaling
            # ConvNeXt is heavy. Keep batch sizes bounded so you don't OOM (Out Of Memory)
            crop_size=trial.suggest_categorical("crop_size", [384, 480, 512]),
            batch_size=trial.suggest_categorical("batch_size", [4, 8, 12]), 
            val_batch_size=1,

            # 3. Learning Rate & Scheduling
            # Log scale is best for learning rates. Searches around your 0.00065 base.
            lr=trial.suggest_float("lr", 1e-4, 2e-3, log=True),
            lr_schedule='clipped_exp',
            scheduler_kwargs={
                'decay_rate': trial.suggest_float("decay_rate", 0.90, 0.99),
                'min_lr_pct': trial.suggest_float("min_lr_pct", 0.005, 0.05),
            },

            # 4. Composite Loss Parameters 
            # Centered around your baseline: ssim=0.3, alpha=0.81, gamma=3.17, delta=5
            loss_function='mask_mse_ssim',
            ssim_weight=trial.suggest_float("ssim_weight", 1*1, 1*2.5),
            mse_weight=trial.suggest_float("mse_weight", 1e-6*1, 1e-6*2),
            mask_loss_weight=trial.suggest_float("mask_loss_weight", 10*0.5, 10*1.0),  # Anchor weight (keep fixed, tune others relative to this)
            mask_loss_alpha=trial.suggest_float("mask_loss_alpha", 0.6, 0.95),
            mask_loss_gamma=trial.suggest_float("mask_loss_gamma", 2.0, 4.0),
            huber_delta=trial.suggest_float("huber_delta", 1.0, 10),
            gt_mask_threshold=0,

            # 5. Regularization (Optional but recommended for ConvNeXt)
            dropout=trial.suggest_float("dropout", 0.0, 0.4),
            l2_reg=trial.suggest_float("l2_reg", 1e-4, 1e-3, log=True),

            suggested_params=True
        )

        # 6. Unfrozen Blocks Logic
        # Wrapped in a try/except so Optuna doesn't crash if 'tu-convnext_small' 
        # isn't explicitly mapped in your registries.UNFROZEN dictionary yet.
        unfrozen = trial.suggest_int("unfrozen", 0, 4)
        try:
            backbone_key = next(e for e in registries.UNFROZEN.keys() if str(e).startswith(suggested['backbone']))
            suggested['unfrozen_blocks'] = registries.UNFROZEN.get(backbone_key, [])[:unfrozen]
        except StopIteration:
            suggested['unfrozen_blocks'] = None

        return cls(**suggested)
    
    def to_dict(self, flatten=False, to_str=False, nested=True) -> Dict[str, Any]:
        """Convert the current parameter bundle to a dictionary representation.

        Args:
            flatten (bool): Whether to flatten nested dictionaries into dot-delimited keys.
            to_str (bool): Whether to coerce dictionary keys and values to strings.
            nested (bool): Whether to wrap values under a top-level ``params`` key.

        Returns:
            Dict[str, Any]: A serializable dictionary representation of the parameter set.
        """
        params_dict = {'params': asdict(self)} if nested else asdict(self)
        if flatten:
            params_dict = helpers.flatten_dict(params_dict, to_str=to_str)
        if not nested and to_str:
            params_dict = helpers.dict_to_str(params_dict)
        return params_dict
    
    def to_json(self, file_path: str, flatten=False, to_str=False, indent=4, meta={}):
        """Persist the parameter object to a JSON file.

        Args:
            file_path (str): Destination file path.
            flatten (bool): Whether to flatten nested dictionaries before serialization.
            to_str (bool): Whether to convert dictionary keys/values to strings.
            indent (int): Pretty-print indentation passed to ``json.dump``.
            meta (dict): Additional metadata to store alongside the parameter payload.

        Returns:
            None: The JSON file is written to disk.
        """
        import json
        data = self.to_dict(flatten=flatten, to_str=to_str)
        data.update({'meta': meta})
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=indent)
    
    @classmethod
    def from_dict(cls, params_dict: dict):
        """Reconstruct a parameter object from a serialized dictionary.

        Args:
            params_dict (dict): Configuration dictionary, potentially nested under a
                ``params`` key produced by ``to_dict``.

        Returns:
            BaseParams: Rehydrated parameter object.
        """
        if params_dict.get('params', None):
            return cls(**params_dict['params'])
        params_dict = helpers.unflatten_dict({k: v for k, v in params_dict.items() if str(k).casefold().startswith('params')}).get('params', params_dict)
        return cls(**params_dict)
    
    @classmethod
    def from_json(cls, file_path: str):
        """Load a parameter object from a JSON file.

        Args:
            file_path (str): Path to a JSON-serialized ``BaseParams`` payload.

        Returns:
            BaseParams: Deserialized parameter instance.

        Raises:
            FileNotFoundError: If the provided JSON file does not exist.
            json.JSONDecodeError: If the file contents are not valid JSON.
        """
        import json
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return cls.from_dict(data)